# Generated by Django 5.2.11 on 2026-03-13 19:48

import django.db.models.deletion
import random
import string
import uuid
from django.conf import settings
from django.db import migrations, models


def migration_generate_transaction_id():
    """Stable migration-local default to avoid runtime imports from app models."""
    return "TXN" + "".join(random.choices(string.digits, k=10))


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(default=migration_generate_transaction_id, max_length=20, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('payment_method', models.CharField(choices=[('card', 'Credit Card'), ('upi', 'UPI'), ('bank', 'Bank Transfer')], max_length=20)),
                ('payment_status', models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('membership_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('payment_details', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-registration_date'],
            },
        ),
    ]
