# Generated by Django 5.2.12 on 2026-04-01 05:53

import payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_payment_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='transaction_id',
            field=models.CharField(default=payments.models.generate_transaction_id, max_length=20, unique=True),
        ),
    ]
