# Generated by Django 5.2.12 on 2026-04-11 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_registrationsequence_alter_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubscription',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.payment'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('failed', 'Failed'), ('expired', 'Expired')], db_index=True, default='created', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentsubscription',
            name='status',
            field=models.CharField(db_index=True, default='ACTIVE', max_length=20),
        ),
        migrations.DeleteModel(
            name='StudentPayment',
        ),
    ]
