# Generated by Django 5.2.12 on 2026-04-13 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_alter_payment_status'),
        ('payments', '0010_alter_studentsubscription_payment_and_more'),
    ]

    operations = [
    ]
