from django.db import models

# here is the model for pre-application form data, which will be stored in the database when a student submits the form.

class PreApplication(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)

    email = models.EmailField()

    whatsapp_no = models.CharField(max_length=13)
    alternate_phone = models.CharField(max_length=13, blank=True, null=True)

    birthplace_state = models.CharField(max_length=100)
    qualification = models.CharField(max_length=100)

    specialization = models.CharField(max_length=100)

    college_name = models.CharField(max_length=150)
    college_state = models.CharField(max_length=100)

    passing_year = models.CharField(max_length=4)

    preferred_time = models.CharField(max_length=50)
    verified = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

# here is the referal code model, which will be used to store the referal codes generated by the admin , by verifying the user.
class ReferalCode(models.Model):
    student = models.OneToOneField(PreApplication, on_delete=models.CASCADE, related_name='referal_codes')
    code = models.CharField(max_length=10, unique=True)
    is_used = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
