# Generated by Django 5.2.11 on 2026-03-28 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_application_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoolDown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooldown_days', models.IntegerField(default=10)),
            ],
        ),
    ]
