# Generated by Django 5.2.11 on 2026-03-28 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_cooldown'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='cooldown_days_used',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
