# Generated by Django 6.0.3 on 2026-04-03 08:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_application_cooldown_days_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='cooldown_days_used',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(365)]),
        ),
        migrations.AlterField(
            model_name='cooldown',
            name='cooldown_days',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(365)]),
        ),
    ]
