# Generated by Django 6.0.3 on 2026-04-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_alter_application_cooldown_days_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
