# Generated by Django 5.2.11 on 2026-03-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_role', models.CharField(max_length=255)),
                ('package', models.DecimalField(decimal_places=2, max_digits=10)),
                ('department', models.CharField(max_length=255)),
                ('total_vacancies', models.PositiveIntegerField()),
                ('experience', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('job_mode', models.CharField(choices=[('Remote', 'Remote'), ('Hybrid', 'Hybrid'), ('On-site', 'On-site')], max_length=20)),
                ('job_description', models.TextField()),
                ('skills_required', models.TextField()),
                ('eligibility', models.TextField()),
            ],
        ),
    ]
