# Generated by Django 6.0.3 on 2026-04-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='package',
            field=models.CharField(max_length=20),
        ),
    ]
