# """
# Django settings for crtd project.

# Generated by 'django-admin startproject' using Django 5.2.1.

# For more information on this file, see
# https://docs.djangoproject.com/en/5.2/topics/settings/

# ?https://docs.djangoproject.com/en/5.2/ref/settings/
# """
# from pathlib import Path
# import os
# from dotenv import load_dotenv
# import dj_database_url

# # Load environment variables from .env file
# # Explicitly specify the path to ensure it's found
# ENV_FILE = Path(__file__).resolve().parent.parent / '.env'
# load_dotenv(ENV_FILE, encoding='utf-8-sig')

# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent


# #razorpay configuration
# RAZORPAY_KEY_ID=os.getenv("RAZORPAY_KEY_ID")
# RAZORPAY_KEY_SECRET=os.getenv("RAZORPAY_KEY_SECRET")
# RAZORPAY_WEBHOOK_SECRET=os.getenv("RAZORPAY_WEBHOOK_SECRET")


# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# # SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-vo@zl!k(=a(ixsgs+g%z!a8$r)ag(r#oz4sa&1*^kg@x3ebs%a'

# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

# ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost').split(',')


# # Application definition

# INSTALLED_APPS = [
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
#     'rest_framework',
#     'drf_yasg',
#     'pre_application',
#     'accounts',
#     'Student',
#     'admin_panel',
#     'jobs.apps.JobsConfig',
#     'payments',
# ]

# MIDDLEWARE = [
#     'django.middleware.security.SecurityMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
# ]

# ROOT_URLCONF = 'crtd.urls'

# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [BASE_DIR / 'templates'],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]

# WSGI_APPLICATION = 'crtd.wsgi.application'


# # Database
# # https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASE_URL = os.getenv("DATABASE_URL")

# if not DATABASE_URL:
#     # Fallback to SQLite for development if DATABASE_URL is not set
#     DATABASES = {
#         'default': {
#             'ENGINE': 'django.db.backends.sqlite3',
#             'NAME': BASE_DIR / 'db.sqlite3',
#         }
#     }
# else:
#     DATABASES = {
#         'default': dj_database_url.parse(
#             DATABASE_URL,
#             conn_max_age=600,
#         )
#     }



# # Password validation
# # https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]


# # Internationalization
# # https://docs.djangoproject.com/en/5.2/topics/i18n/

# LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'

# USE_I18N = True

# USE_TZ = True


# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/5.2/howto/static-files/

# STATIC_URL = 'static/'
# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# # Default primary key field type
# # https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# # Email Configuration
# # https://docs.djangoproject.com/en/5.2/topics/email/


#     # Production: Use SMTP
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = (
#     os.environ.get('EMAIL_USER')
#     or os.environ.get('\ufeffEMAIL_USER')
#     or os.environ.get('EMAIL_HOST_USER')
# )
# EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_PASS') or os.environ.get('EMAIL_HOST_PASSWORD')

# if EMAIL_HOST_PASSWORD:
#     # Gmail app-passwords are often copied with spaces between 4-char groups.
#     EMAIL_HOST_PASSWORD = EMAIL_HOST_PASSWORD.replace(' ', '')

# DEFAULT_FROM_EMAIL = 'muharibfah@gmail.com'


# AUTH_USER_MODEL = 'accounts.CustomUser'

# # -------------------------------------------------------
# # DRF + JWT CONFIGURATION
# # -------------------------------------------------------

# REST_FRAMEWORK = {
#     # Use JWT for authentication
#     'DEFAULT_AUTHENTICATION_CLASSES': (
#         'rest_framework_simplejwt.authentication.JWTAuthentication',
#         "rest_framework.authentication.SessionAuthentication",
#     ),

#     # Default permission (can override in views later)
#     'DEFAULT_PERMISSION_CLASSES': (
#         'rest_framework.permissions.IsAuthenticated',
#     ),
# }


# # GOOGLE OAUTH CONFIGURATION
# GOOGLE_OAUTH_CLIENT_ID = os.getenv('GOOGLE_OAUTH_CLIENT_ID')
# GOOGLE_OAUTH_CLIENT_SECRET = os.getenv('GOOGLE_OAUTH_CLIENT_SECRET')


# # -------------------------------------------------------
# # CELERY CONFIGURATION
# # -------------------------------------------------------
# # Celery is used for asynchronous task processing, primarily for email sending.
# # This allows the application to handle 1 lakh+ concurrent users by scaling
# # Celery workers horizontally.

# # Message Broker - Redis
# # Redis performs both message broker (task queue) and result backend roles
# CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')
# CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')

# # Task Configuration
# CELERY_TASK_SERIALIZER = 'json'
# CELERY_ACCEPT_CONTENT = ['json']
# CELERY_RESULT_SERIALIZER = 'json'
# CELERY_TIMEZONE = 'UTC'
# CELERY_ENABLE_UTC = True

# # Task Tracking
# CELERY_TASK_TRACK_STARTED = True

# # Time Limits
# CELERY_TASK_TIME_LIMIT = 30 * 60  # Hard limit: 30 minutes
# CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60  # Soft limit: 25 minutes

# # Results
# CELERY_RESULT_EXPIRES = 3600  # Results expire after 1 hour

# # Worker Configuration
# CELERY_WORKER_PREFETCH_MULTIPLIER = 4
# CELERY_WORKER_MAX_TASKS_PER_CHILD = 1000

# # Retry Configuration
# CELERY_TASK_AUTORETRY_FOR = (Exception,)
# CELERY_TASK_MAX_RETRIES = 3

# # Beat Schedule (Periodic Tasks)
# CELERY_BEAT_SCHEDULE = {
#     'clean-expired-otps': {
#         'task': 'utils.tasks.cleanup_expired_otps',
#         'schedule': 3600,  # Every hour (in seconds)
#         'options': {'queue': 'default'},
#     },
#     'process-pending-emails': {
#         'task': 'utils.tasks.process_pending_emails',
#         'schedule': 300,  # Every 5 minutes (in seconds)
#         'options': {'queue': 'default'},
#     },
# }

# # -------------------------------------------------------
# # Queues Configuration
# # -------------------------------------------------------
# # Define task queues for different purposes
# CELERY_QUEUES = {
#     'default': {
#         'exchange': 'default',
#         'binding_key': 'default',
#         'queue_arguments': {
#             'x-max-priority': 10,  # Max priority level
#         }
#     },
#     'email': {
#         'exchange': 'email',
#         'binding_key': 'email',
#         'queue_arguments': {
#             'x-max-priority': 10,
#         }
#     },
#     'scheduled': {
#         'exchange': 'scheduled',
#         'binding_key': 'scheduled',
#     },
# }

# # Default queue for tasks
# CELERY_DEFAULT_QUEUE = 'default'


# SWAGGER_SETTINGS = {
#     "USE_SESSION_AUTH": False,
#     "SECURITY_REQUIREMENTS": [{"Bearer": []}],
#     "SECURITY_DEFINITIONS": {
#         "Bearer": {
#             "type": "apiKey",
#             "name": "Authorization",
#             "in": "header",
#             "description": 'JWT Authorization header using the Bearer scheme. Example: "Bearer <token>"',
#         }
#     },
# }
from pathlib import Path
import os
from dotenv import load_dotenv
import dj_database_url

# -------------------------------------------------------
# BASE + ENV
# -------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

ENV_FILE = BASE_DIR / '.env'
load_dotenv(ENV_FILE, encoding='utf-8-sig')

# -------------------------------------------------------
# SECURITY
# -------------------------------------------------------
SECRET_KEY = os.getenv('SECRET_KEY', 'unsafe-secret-key')

DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '127.0.0.1,localhost').split(',')

# -------------------------------------------------------
# RAZORPAY CONFIG
# -------------------------------------------------------
RAZORPAY_KEY_ID = os.getenv("RAZORPAY_KEY_ID")
RAZORPAY_KEY_SECRET = os.getenv("RAZORPAY_KEY_SECRET")
RAZORPAY_WEBHOOK_SECRET = os.getenv("RAZORPAY_WEBHOOK_SECRET")

# -------------------------------------------------------
# APPLICATIONS
# -------------------------------------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party
    'corsheaders',
    'rest_framework',
    'drf_yasg',

    # Local apps
    'accounts',
    'Student',
    'pre_application',
    'admin_panel',
    'admin_analytics',
    'applications',
    'jobs.apps.JobsConfig',
    'payments',
    'subscription',
]

# -------------------------------------------------------
# MIDDLEWARE
# -------------------------------------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # important
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# -------------------------------------------------------
# CORS CONFIG
# -------------------------------------------------------
CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.getenv(
        'CORS_ALLOWED_ORIGINS',
        'http://localhost:3000'
    ).split(',')
]

CORS_ALLOW_CREDENTIALS = True

# -------------------------------------------------------
# URLS / TEMPLATES
# -------------------------------------------------------
ROOT_URLCONF = 'crtd.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'crtd.wsgi.application'

# -------------------------------------------------------
# DATABASE
# -------------------------------------------------------
DATABASE_URL = os.getenv("DATABASE_URL")

if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL, conn_max_age=600)
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# -------------------------------------------------------
# PASSWORD VALIDATION
# -------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# -------------------------------------------------------
# INTERNATIONALIZATION
# -------------------------------------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'

USE_I18N = True
USE_TZ = True

# -------------------------------------------------------
# STATIC FILES
# -------------------------------------------------------
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# -------------------------------------------------------
# DEFAULT PK
# -------------------------------------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# -------------------------------------------------------
# AUTH USER MODEL
# -------------------------------------------------------
AUTH_USER_MODEL = 'accounts.CustomUser'

# -------------------------------------------------------
# EMAIL CONFIG
# -------------------------------------------------------
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = (
    os.getenv('EMAIL_USER')
    or os.getenv('\ufeffEMAIL_USER')
    or os.getenv('EMAIL_HOST_USER')
)

EMAIL_HOST_PASSWORD = (
    os.getenv('EMAIL_PASS')
    or os.getenv('EMAIL_HOST_PASSWORD')
)

if EMAIL_HOST_PASSWORD:
    EMAIL_HOST_PASSWORD = EMAIL_HOST_PASSWORD.replace(' ', '')

DEFAULT_FROM_EMAIL = os.getenv(
    'DEFAULT_FROM_EMAIL',
    EMAIL_HOST_USER or 'noreply@crtdtechnologies.com'
)

# -------------------------------------------------------
# DRF + JWT
# -------------------------------------------------------
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

# -------------------------------------------------------
# GOOGLE OAUTH
# -------------------------------------------------------
GOOGLE_OAUTH_CLIENT_ID = os.getenv('GOOGLE_OAUTH_CLIENT_ID')
GOOGLE_OAUTH_CLIENT_SECRET = os.getenv('GOOGLE_OAUTH_CLIENT_SECRET')

# -------------------------------------------------------
# CELERY CONFIG
# -------------------------------------------------------
APP_ENV = os.getenv('APP_ENV', 'local').lower()
REDIS_HOST = os.getenv('REDIS_HOST', 'localhost')
REDIS_PORT = os.getenv('REDIS_PORT', '6379')
REDIS_DB = os.getenv('REDIS_DB', '0')

default_redis_url = f'redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}'

# Explicit CELERY_* URLs take priority. Otherwise use REDIS_* pieces.
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL') or default_redis_url
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND') or default_redis_url

# In local/dev environments, normalize docker-compose hostname if someone copied it.
if APP_ENV in ('local', 'dev', 'development'):
    CELERY_BROKER_URL = CELERY_BROKER_URL.replace('redis://redis:', 'redis://localhost:')
    CELERY_RESULT_BACKEND = CELERY_RESULT_BACKEND.replace('redis://redis:', 'redis://localhost:')

CELERY_TASK_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_RESULT_SERIALIZER = 'json'

CELERY_TIMEZONE = 'UTC'
CELERY_ENABLE_UTC = True

CELERY_TASK_TRACK_STARTED = True

CELERY_TASK_TIME_LIMIT = 30 * 60
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60

CELERY_RESULT_EXPIRES = 3600

CELERY_WORKER_PREFETCH_MULTIPLIER = 4
CELERY_WORKER_MAX_TASKS_PER_CHILD = 1000

CELERY_TASK_AUTORETRY_FOR = (Exception,)
CELERY_TASK_MAX_RETRIES = 3

CELERY_BEAT_SCHEDULE = {
    'clean-expired-otps': {
        'task': 'utils.tasks.cleanup_expired_otps',
        'schedule': 3600,
    },
    'process-pending-emails': {
        'task': 'utils.tasks.process_pending_emails',
        'schedule': 300,
    },
}

CELERY_QUEUES = {
    'default': {
        'exchange': 'default',
        'binding_key': 'default',
        'queue_arguments': {'x-max-priority': 10},
    },
    'email': {
        'exchange': 'email',
        'binding_key': 'email',
        'queue_arguments': {'x-max-priority': 10},
    },
    'scheduled': {
        'exchange': 'scheduled',
        'binding_key': 'scheduled',
    },
}

CELERY_DEFAULT_QUEUE = 'default'

# -------------------------------------------------------
# SWAGGER
# -------------------------------------------------------
SWAGGER_SETTINGS = {
    "USE_SESSION_AUTH": False,
    "SECURITY_REQUIREMENTS": [{"Bearer": []}],
    "SECURITY_DEFINITIONS": {
        "Bearer": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header",
            "description": "Bearer <JWT Token>",
        }
    },
}