# Generated by Django 5.2.11 on 2026-03-05 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_email_verified_emailotp'),
        ('accounts', '0003_remove_customuser_email_verified'),
    ]

    operations = [
    ]
