# Generated by Django 5.2.11 on 2026-03-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_universal_otp_user_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('company', 'Company'), ('admin', 'Admin'), ('subadmin', 'Subadmin')], max_length=20),
        ),
    ]
