# Generated by ChatGPT on 2026-04-01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_emailotp_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(
                choices=[
                    ('superadmin', 'Super Admin'),
                    ('sales', 'Sales'),
                    ('student', 'Student'),
                    ('company', 'Company'),
                    ('admin', 'Admin'),
                    ('subadmin', 'Subadmin'),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('dashboard', 'Dashboard'), ('web_update', 'Web Update'), ('enquiry_form', 'Enquiry Form'), ('reference_code', 'Reference Code'), ('sub_admin', 'Sub Admin'), ('total_user_status', 'Total User Status'), ('analytics', 'Analytics'), ('payment', 'Payment'), ('job_applications', 'Job Applications'), ('membership', 'Membership'), ('employee_status', 'Employee Status'), ('sales', 'Sales')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'accounts_module',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SubAdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allowed_modules', models.ManyToManyField(blank=True, to='accounts.module')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_subadmins', to='accounts.customuser')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subadmin_profile', to='accounts.customuser')),
            ],
            options={
                'db_table': 'accounts_subadmin_profile',
            },
        ),
    ]
