# Generated by Django 5.2.12 on 2026-04-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_add_rbac_models_and_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('sales', 'Sales'), ('student', 'Student'), ('company', 'Company'), ('admin', 'Admin'), ('subadmin', 'Subadmin')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='expires_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
