# Generated by Django 5.2.12 on 2026-04-08 16:27

import django.db.models.deletion
from django.db import migrations, models


def backfill_subadmin_module_access(apps, schema_editor):
    SubAdminProfile = apps.get_model('accounts', 'SubAdminProfile')
    SubAdminModuleAccess = apps.get_model('accounts', 'SubAdminModuleAccess')
    through_model = SubAdminProfile.allowed_modules.through

    existing_pairs = set(
        SubAdminModuleAccess.objects.values_list('subadmin_profile_id', 'module_id')
    )
    access_rows = []
    for relation in through_model.objects.all().iterator():
        key = (relation.subadminprofile_id, relation.module_id)
        if key in existing_pairs:
            continue
        access_rows.append(
            SubAdminModuleAccess(
                subadmin_profile_id=relation.subadminprofile_id,
                module_id=relation.module_id,
                is_active=True,
            )
        )
        existing_pairs.add(key)

    if access_rows:
        SubAdminModuleAccess.objects.bulk_create(access_rows)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_customuser_role_alter_emailotp_expires_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubAdminBirthStateScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'accounts_subadmin_birth_state_scope',
            },
        ),
        migrations.CreateModel(
            name='SubAdminCollegeStateScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'accounts_subadmin_college_state_scope',
            },
        ),
        migrations.CreateModel(
            name='SubAdminModuleAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('access_start', models.DateTimeField(blank=True, null=True)),
                ('access_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'accounts_subadmin_module_access',
            },
        ),
        migrations.CreateModel(
            name='SubAdminPassingYearScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passing_year', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'accounts_subadmin_passing_year_scope',
            },
        ),
        migrations.AddField(
            model_name='subadminprofile',
            name='account_access_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subadminprofile',
            name='account_access_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='subadminprofile',
            constraint=models.CheckConstraint(condition=models.Q(('account_access_start__isnull', True), ('account_access_end__isnull', True), ('account_access_start__lte', models.F('account_access_end')), _connector='OR'), name='subadmin_account_window_valid'),
        ),
        migrations.AddField(
            model_name='subadminbirthstatescope',
            name='subadmin_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birth_state_scopes', to='accounts.subadminprofile'),
        ),
        migrations.AddField(
            model_name='subadmincollegestatescope',
            name='subadmin_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_state_scopes', to='accounts.subadminprofile'),
        ),
        migrations.AddField(
            model_name='subadminmoduleaccess',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subadmin_accesses', to='accounts.module'),
        ),
        migrations.AddField(
            model_name='subadminmoduleaccess',
            name='subadmin_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_accesses', to='accounts.subadminprofile'),
        ),
        migrations.AddField(
            model_name='subadminpassingyearscope',
            name='subadmin_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passing_year_scopes', to='accounts.subadminprofile'),
        ),
        migrations.AddIndex(
            model_name='subadminbirthstatescope',
            index=models.Index(fields=['subadmin_profile', 'state_name'], name='subadmin_birth_scope_idx'),
        ),
        migrations.AddConstraint(
            model_name='subadminbirthstatescope',
            constraint=models.UniqueConstraint(fields=('subadmin_profile', 'state_name'), name='uniq_subadmin_birth_state_scope'),
        ),
        migrations.AddIndex(
            model_name='subadmincollegestatescope',
            index=models.Index(fields=['subadmin_profile', 'state_name'], name='subadmin_college_scope_idx'),
        ),
        migrations.AddConstraint(
            model_name='subadmincollegestatescope',
            constraint=models.UniqueConstraint(fields=('subadmin_profile', 'state_name'), name='uniq_subadmin_college_state_scope'),
        ),
        migrations.AddIndex(
            model_name='subadminmoduleaccess',
            index=models.Index(fields=['subadmin_profile', 'module'], name='subadmin_module_idx'),
        ),
        migrations.AddIndex(
            model_name='subadminmoduleaccess',
            index=models.Index(fields=['module', 'is_active'], name='subadmin_module_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='subadminmoduleaccess',
            constraint=models.UniqueConstraint(fields=('subadmin_profile', 'module'), name='uniq_subadmin_module_access'),
        ),
        migrations.AddConstraint(
            model_name='subadminmoduleaccess',
            constraint=models.CheckConstraint(condition=models.Q(('access_start__isnull', True), ('access_end__isnull', True), ('access_start__lte', models.F('access_end')), _connector='OR'), name='subadmin_module_access_window_valid'),
        ),
        migrations.AddIndex(
            model_name='subadminpassingyearscope',
            index=models.Index(fields=['subadmin_profile', 'passing_year'], name='subadmin_year_scope_idx'),
        ),
        migrations.AddConstraint(
            model_name='subadminpassingyearscope',
            constraint=models.UniqueConstraint(fields=('subadmin_profile', 'passing_year'), name='uniq_subadmin_passing_year_scope'),
        ),
        migrations.RunPython(backfill_subadmin_module_access, migrations.RunPython.noop),
    ]
