# Generated by Django 5.2.12 on 2026-04-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_subadminbirthstatescope_subadmincollegestatescope_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subadminmoduleaccess',
            name='subadmin_module_access_window_valid',
        ),
        migrations.RemoveIndex(
            model_name='subadminmoduleaccess',
            name='subadmin_module_active_idx',
        ),
        migrations.RemoveField(
            model_name='subadminmoduleaccess',
            name='access_end',
        ),
        migrations.RemoveField(
            model_name='subadminmoduleaccess',
            name='access_start',
        ),
        migrations.RemoveField(
            model_name='subadminmoduleaccess',
            name='is_active',
        ),
        migrations.AddField(
            model_name='subadminmoduleaccess',
            name='can_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subadminmoduleaccess',
            name='can_view',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='subadminmoduleaccess',
            index=models.Index(fields=['module', 'can_view'], name='subadmin_module_view_idx'),
        ),
        migrations.AddIndex(
            model_name='subadminmoduleaccess',
            index=models.Index(fields=['module', 'can_edit'], name='subadmin_module_edit_idx'),
        ),
        migrations.AddConstraint(
            model_name='subadminmoduleaccess',
            constraint=models.CheckConstraint(condition=models.Q(('can_edit', False), ('can_view', True), _connector='OR'), name='subadmin_module_edit_implies_view'),
        ),
    ]
