# Generated by Django 5.0.6 on 2026-03-13 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referalcode',
            name='is_used',
        ),
        migrations.AddField(
            model_name='referalcode',
            name='status',
            field=models.CharField(choices=[('not_used', 'Account Not Created'), ('account_created', 'Account Created'), ('membership_pending', 'Membership Not Completed'), ('membership_completed', 'Membership Completed')], default='not_used', max_length=25),
        ),
        migrations.AlterField(
            model_name='referalcode',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reference_code', to='pre_application.preapplication'),
        ),
    ]
