# Generated by Django 5.2.1 on 2026-02-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preapplication',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
