# Generated by Django 5.2.12 on 2026-04-01 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_application', '0005_restore_referalcode_is_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referalcode',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referal_codes', to='pre_application.preapplication'),
        ),
    ]
