# Generated by Django 5.2.12 on 2026-04-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_application', '0006_alter_referalcode_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='preapplication',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', 'Pending'),
                    ('completed', 'Completed'),
                    ('not interested', 'Not Interested'),
                ],
                default='pending',
                max_length=20,
            ),
        ),
    ]
