# Generated by Django 5.2.12 on 2026-04-07 11:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_application', '0008_preapplication_soft_delete_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='preapplication',
            index=models.Index(fields=['email'], name='preapp_email_idx'),
        ),
        migrations.AddIndex(
            model_name='preapplication',
            index=models.Index(fields=['is_deleted'], name='preapp_deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='preapplication',
            index=models.Index(fields=['created_at'], name='preapp_created_idx'),
        ),
        migrations.AddIndex(
            model_name='preapplication',
            index=models.Index(fields=['is_deleted', 'created_at'], name='preapp_del_created_idx'),
        ),
        migrations.AddIndex(
            model_name='referalcode',
            index=models.Index(fields=['status'], name='referral_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='preapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('email',), name='uniq_active_preapp_email'),
        ),
    ]
