# Generated by Django 5.2.12 on 2026-04-08 16:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_application', '0009_preapplication_preapp_email_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='preapplication',
            name='birthplace_state',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='preapplication',
            name='college_state',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='preapplication',
            name='passing_year',
            field=models.CharField(db_index=True, max_length=4),
        ),
    ]
