# Generated by Django 5.0.6 on 2026-03-13 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pre_application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnquiryAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry_token', models.CharField(editable=False, max_length=12, unique=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('done', 'Enquiry Done'), ('pending', 'Pending'), ('not_interested', 'Not Interested')], default='received', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enquiry_analytics', to='pre_application.preapplication')),
            ],
        ),
    ]
