# Generated by Django 5.2.11 on 2026-03-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_analytics', '0002_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPartners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_partners', models.IntegerField(default=0)),
            ],
        ),
    ]
