# Generated by Django 5.2.12 on 2026-04-06 00:00

from django.db import migrations, models


def sync_enquiry_tokens(apps, schema_editor):
    EnquiryAnalytics = apps.get_model("admin_analytics", "EnquiryAnalytics")

    for analytics in EnquiryAnalytics.objects.select_related("student").all():
        analytics.enquiry_token = analytics.student.enquiry_token
        analytics.save(update_fields=["enquiry_token"])


class Migration(migrations.Migration):

    dependencies = [
        ("admin_analytics", "0003_companypartners"),
        ("pre_application", "0007_preapplication_status"),
    ]

    operations = [
        migrations.RunPython(sync_enquiry_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="enquiryanalytics",
            name="enquiry_token",
            field=models.CharField(editable=False, max_length=9, unique=True),
        ),
    ]
