# Generated by Django 5.2.12 on 2026-04-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_analytics', '0004_sync_enquiryanalytics_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiryanalytics',
            name='enquiry_token',
            field=models.CharField(editable=False, max_length=12, unique=True),
        ),
    ]
