# Generated by Django 5.2.12 on 2026-04-13 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_analytics', '0005_alter_enquiryanalytics_enquiry_token'),
        ('jobs', '0004_migrate_testimonials_from_admin_analytics'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
