# Generated by Django 5.2.1 on 2026-02-28 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentCareerPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_job_role', models.CharField(blank=True, max_length=150, null=True)),
                ('work_mode', models.CharField(blank=True, max_length=50, null=True)),
                ('preferred_time', models.CharField(blank=True, max_length=50, null=True)),
                ('experience', models.CharField(blank=True, max_length=50, null=True)),
                ('expected_ctc', models.CharField(blank=True, max_length=50, null=True)),
                ('student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='career_preference', to='Student.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(blank=True, max_length=100, null=True)),
                ('specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('college_name', models.CharField(blank=True, max_length=150, null=True)),
                ('college_state', models.CharField(blank=True, max_length=100, null=True)),
                ('passing_year', models.CharField(blank=True, max_length=4, null=True)),
                ('cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='education', to='Student.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentPersonalDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('whatsapp_no', models.CharField(blank=True, max_length=13, null=True)),
                ('alternate_phone', models.CharField(blank=True, max_length=13, null=True)),
                ('birthplace_state', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('permanent_state', models.CharField(blank=True, max_length=100, null=True)),
                ('permanent_city', models.CharField(blank=True, max_length=100, null=True)),
                ('permanent_pin_code', models.CharField(blank=True, max_length=10, null=True)),
                ('permanent_address', models.TextField(blank=True, null=True)),
                ('current_state', models.CharField(blank=True, max_length=100, null=True)),
                ('current_city', models.CharField(blank=True, max_length=100, null=True)),
                ('current_pin_code', models.CharField(blank=True, max_length=10, null=True)),
                ('current_address', models.TextField(blank=True, null=True)),
                ('student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_detail', to='Student.student')),
            ],
        ),
    ]
