# Generated by Django 5.2.11 on 2026-03-27 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_remove_studentotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_profile_complete',
            field=models.BooleanField(default=False),
        ),
    ]
