# Generated by Django 5.2.12 on 2026-04-01 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0004_student_is_profile_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_profile_complete',
        ),
    ]
