# Generated by Django 4.2.27 on 2026-04-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0005_remove_student_is_profile_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
    ]
