# Generated by Django 6.0.3 on 2026-04-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0005_remove_student_is_profile_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_profile_complete',
            field=models.BooleanField(default=False),
        ),
    ]
