# Generated by Django 6.0.3 on 2026-04-05 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0006_student_is_profile_complete'),
        ('Student', '0006_student_profile_completed'),
    ]

    operations = [
    ]
