# Generated by Django 6.0.3 on 2026-04-05 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0007_merge_20260405_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_profile_complete',
        ),
    ]
