# Generated by Django 5.2.12 on 2026-04-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0008_remove_student_is_profile_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenteducation',
            name='college_state',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studenteducation',
            name='passing_year',
            field=models.CharField(blank=True, db_index=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='studentpersonaldetail',
            name='birthplace_state',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
